facts = {
    "Skin": {
        "Acne vulgaris": "Blocked follicles + P. acnes inflammation",
        "Impetigo": "Highly contagious blisters; S. aureus or S. pyogenes",
        "Folliculitis": "Hair follicle infection; S. aureus",
        "Furuncles": "Walled-off abscess from folliculitis",
        "Carbuncles": "Joined furuncles; deep infection",
        "Scalded Skin Syndrome": "Exfoliatins cause skin peeling",
        "Toxic Shock Syndrome": "TSST toxin; whole-body shock",
        "Erysipelas": "Hot, red, raised facial rash; S. pyogenes",
        "Necrotizing Fasciitis": "Flesh-eating strep; rapid tissue death",
        "Papillomas": "Warts from cutaneous HPV",
        "HPV Cancers": "Strains 16/18 linked to cervical cancer",
        "Smallpox": "Eradicated; severe pox lesions",
        "Herpes (oral/genital/neonatal)": "HSV latency + blisters",
        "Varicella": "Chickenpox from VZV, respiratory spread",
        "Zoster": "Shingles; reactivated VZV along nerves",
        "Measles": "Koplik spots + full-body rash",
        "Rubella": "Mild rash, severe congenital effects"
    },
    "Respiratory": {
        "Streptococcal Pharyngitis": "Strep throat; no cough, risk of RF",
        "Scarlet Fever": "Erythrogenic toxin; sandpaper rash",
        "Diphtheria": "Gray membrane in throat; exotoxin",
        "Common Cold": "200+ viruses; mostly rhinovirus",
        "Pertussis": "Whooping cough; paralyzes cilia",
        "Tuberculosis": "Acid-fast M. tuberculosis; Ghon complexes",
        "Pneumococcal Pneumonia": "Rust sputum; S. pneumoniae",
        "Atypical Pneumonia": "Walking pneumonia; Mycoplasma",
        "Legionnaire’s Disease": "Legionella from AC units",
        "RSV Disease": "Most common pneumonia in infants",
        "Influenza": "Antigenic drift & shift; pandemics",
        "Avian Influenza": "H5N1; deadly bird-to-human flu",
        "SARS": "2003 outbreak; coronavirus; no vaccine",
        "COVID-19": "Pandemic; SARS-CoV-2; ACE2 binding"
    },
    "Cardio/Nervous": {
        "Sepsis & Septic Shock": "Immune overreaction → organ failure",
        "Acute Bacterial Endocarditis": "IV drug use; S. aureus",
        "Subacute Bacterial Endocarditis": "Oral streptococci + valve disease",
        "Anthrax": "B. anthracis; black eschar; bioweapon",
        "Gas Gangrene": "C. perfringens; gas bubbles in tissue",
        "Plague": "Y. pestis; buboes; flea vector",
        "Spotted Fever": "Rickettsia; tick-borne; rash on palms/soles",
        "Infectious Mononucleosis": "EBV; swollen lymph nodes",
        "Ebola Virus Disease": "Hemorrhagic fever; 30-70% fatal",
        "HIV/AIDS": "Retrovirus; destroys CD4+ T cells",
        "Bacterial Meningitis": "Neisseria, Hib, S. pneumo; fatal if untreated",
        "Tetanus": "Rigid paralysis; deep wound + exotoxin",
        "Botulism": "Flaccid paralysis; food toxin or wound",
        "Rabies": "100% fatal post-symptom; bullet virus",
        "Malaria": "Plasmodium; relapsing fevers; mosquito",
        "Cytomegalovirus Disease": "Herpesvirus; congenital defects"
    },
    "GI/STI/Urinary": {
        "Food Poisoning (B. cereus)": "Pre-formed rice toxins: emetic or diarrheal",
        "Cholera": "Rice-water stool; V. cholerae toxin",
        "C. diff Colitis": "Pseudomembranous colitis post-antibiotics",
        "Listeriosis": "Listeria in cold food; neonatal meningitis",
        "Salmonellosis": "Diarrhea; often from chicken or eggs",
        "Typhoid Fever": "Salmonella Typhi; high fever, rash",
        "Hepatitis A": "Fecal-oral, acute liver infection",
        "Rotavirus Diarrhea": "Infant diarrhea; winter season",
        "Norovirus Disease": "Cruise ship vomiting virus",
        "Bacterial Vaginosis": "Dysbiosis, fishy odor, not STI",
        "Chlamydial Disease": "Obligate intracellular; infertility risk",
        "Syphilis": "Stages: chancre → rash → latency → CNS",
        "UTI": "E. coli; short female urethra risk",
        "Hepatitis B": "Blood/sex; liver cancer risk",
        "Hepatitis C": "Silent liver killer; leading cause of transplants",
        "Aflatoxin-related Liver Cancer": "Aspergillus toxin in moldy grain"
    }
}
